
# Deployment
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: smartscale
spec:
  selector:
    matchLabels:
      app: smartscale
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    #minReadySeconds: 5
  template: 
    metadata:
      labels:
        app: smartscale
    spec:
      containers:
        - name: smartscale
          image: saggad/smartscale:1.2
          env:
            - name: spring.profiles.active
              value: "Deployment"
            - name: spring.datasource.url
              value: "jdbc:mysql://172.17.0.4:3306/springsql"
          ports:
            - containerPort: 8080
              name: server
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: smartscale-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  clusterIP: 10.96.0.4
  selector:
    app: smartscale
  type: NodePort

---

# Replication Controller
apiVersion: v1
kind: ReplicationController
metadata:
  name: smartscale-replica
spec:
  #replicas: 3
  template:
    metadata:
      labels:
        app: smartscale
    spec:
      containers:
        - name: smartscale
          image: saggad/smartscale:1.2
          env:
            - name: spring.profiles.active
              value: "Deployment"
            - name: spring.datasource.url
              value: "jdbc:mysql://172.17.0.4:3306/springsql"
          ports:
            - containerPort: 8080
              name: server
#---
## Horizontal Autoscaler
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: smartscale-autoscaler
#  namespace: default
#spec:
#  scaleTargetRef:
#    apiVersion: extensions/v1beta1
#    kind: Deployment
#    name: smartscale
#  minReplicas: 2
#  maxReplicas: 4