apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    version: "1.0"
    environment: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: "1.0"
      environment: Deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: "1.0"
        environment: Deployment
    spec:
      containers:
        - image: saggad/springsql:1.3
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: user
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage

#========================= EXPOSE SERVICE ======================================
# sudo kubectl expose deployment mysql --type=LoadBalancer --name=mysql-exposed

# ============ Allocate cpu and memory ==========
# sudo minikube start --vm-driver=virtualbox --cpus 6 --memory 3192